from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class TaskStoreProtocol(Protocol):
    def save_task(self, task: Any, mode: str | None = None) -> None: ...
    def get_task(self, task_id: str) -> dict[str, Any] | None: ...
    def list_tasks(self, limit: int = 20) -> list[dict[str, Any]]: ...
    def update_task_status(self, task_id: str, status: str, result: dict[str, Any] | None = None) -> dict[str, Any] | None: ...


@runtime_checkable
class ApprovalStoreProtocol(Protocol):
    def create_approval(self, task_id: str, tool_name: str, action: str, **kwargs: Any) -> Any: ...
    def get_approval(self, approval_id: str) -> dict[str, Any] | None: ...
    def list_approvals(self, status: str | None = None, limit: int = 20) -> list[dict[str, Any]]: ...
    def decide_approval(self, approval_id: str, approved: bool, decided_by: str = "admin", reason: str = "") -> dict[str, Any] | None: ...
    def update_payload(self, approval_id: str, payload_update: dict[str, Any]) -> dict[str, Any] | None: ...


@runtime_checkable
class AuditStoreProtocol(Protocol):
    def append(self, event: Any) -> Any: ...
    def get_event(self, event_id: str) -> dict[str, Any] | None: ...
    def query_events(self, **kwargs: Any) -> list[dict[str, Any]]: ...


@runtime_checkable
class MetricsStoreProtocol(Protocol):
    def record_task_metric(self, **kwargs: Any) -> None: ...
    def record_tool_metric(self, **kwargs: Any) -> None: ...
    def record_token_usage(self, **kwargs: Any) -> None: ...
    def get_task_metrics_summary(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_tool_metrics_summary(self, **kwargs: Any) -> dict[str, Any]: ...
    def get_token_usage_summary(self, **kwargs: Any) -> dict[str, Any]: ...
